[google]
client_id = "447038806959-omnare5tact399201l9vtk1tsj0ncvab.apps.googleusercontent.com"
client_secret = "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"
refresh_token = "1//0gawisYYdlj13CgYIARAAGBASNwF-L9IrRYRiEzAZOcIfn9fJSZ6sHznfYAg_KkZ-ewJrXKP0wlsMbI8Lx0xVRF0Ocf1B1jJFRCI"
token_uri = "https://oauth2.googleapis.com/token"

